# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa21db43f3617829828d25a48734f1c3936c249fcfa99462f17edff5a006ec0e602292253e0562faf0bd7c3c5e8f40ed99fd6833b2e0131cef04ef41e16a07e

test:
  secret_key_base: 7dbfba1ae554aa0e41d00a3f751787b38ea16e95fb4bd76e4dbebbdc67d3b7a7df4c2ea8181ce8f363a47652d6af13264a766db4a24354c62b1393151327b5e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
